spiceqa/tp-spice

spice/tests/rv_session.py
Signed-off-by: Tomas Jamrisko <tjamrisk@redhat.com>
=> rv_session.py: Calling function by new name (refactor failed -.-)

docs/source/quickstart.rst, spice/deps/helper_cb.py
Modified helper file to be functional with 282141 test case.
quickstart.rts is provisional draft.
=> 'TEXT' correction to 'STRING' and quickstart guide

spice/cfg/tests-variants.cfg
To be in tune with 282137 and 282138 TCMS test cases.
=> Changed kbytes value from 100 to 256.

spice/cfg/tests-variants.cfg
=> Added BMP, text copypaste tests

docs/source/quickstart.rst
=> Updated quickstart guide

spice/lib/vm_actions_linux.py, spice/tests/rv_copypaste.py
Everything except tests with 'negative' option in copy-paste tests were fixed.
=> fixed copy-paste tests

spice/lib/vm_actions_linux.py, spice/tests/rv_connect.py, spice/tests/rv_gui.py
=> fix for rv_gui tests

spice/lib/vm_actions.py, spice/lib/vm_actions_linux.py, spice/tests/rv_connect.py, spice/tests/rv_connect_fail.py, spice/tests/rv_gui.py
=> fix rv_gui.py and dependencies

spice/lib/vm_actions_linux.py, spice/tests/rv_gui.py
=> Corrected indentation for new ssn

spice/client-tests/rv7.py
=> Corrected positional argument for @retries

spice/cfg/tests-variants.cfg, spice/client-tests/fs_on_off.py
=> 326010 and 326011 tests for switching on-off fullscreen modified

spice/client-tests/fs_on_off.py, spice/client-tests/rv7.py
=> Various fixes in rv tests

spice/cfg/tests-variants.cfg, spice/client-tests/zoom.py, spice/tests/rv_gui.py
=> fixes and enhancements for zoom tests

spice/cfg/tests-variants.cfg, spice/client-tests/zoom.py, spice/tests/rv_gui.py
=> Improved zoom tests.

spice/cfg/tests-variants.cfg
I have unintentionally modified test case numbers in my previous pull request.
=> Corrected wrong test case numbers

spice/client-tests/zoom.py
=> Unmaximize window before zoom test

spice/lib/vm_actions_linux.py, spice/lib/vm_actions_rv.py, spice/tests/rv_fullscreen.py
=> Fixed connection to guest in fullscreen test

spice/lib/utils.py
=> Added string conversion

spice/cfg/tests-variants.cfg, spice/client-tests/rv6.py, spice/tests/rv_gui.py
=> rv_gui for rhel6 correction

spice/cfg/tests-variants.cfg
=> Added copypaste testcases

spice/cfg/tests-variants.cfg
=> Added some copypaste tests according to our tcms

spice/lib/vm_actions_linux.py
=> Corrected indent

requirements-travis.txt
=> Restricted Pillow version for python26

requirements-travis.txt
=> Corrected Python version condition

spice/tests/rv_copypaste.py
=> Removed not used logger.

spice/cfg/tests.cfg, spice/unattended/RHEL-6-spice.ks, spice/unattended/RHEL-7-spice.ks
=> Add PIL to kickstart, correct RHEL6.devel repo

spice/cfg/tests-variants.cfg, spice/lib/vm_actions_linux.py, spice/tests/vm_listen.py
Enhancement of https://github.com/spiceqa/tp-spice/pull/52
=> Test of listening ports, closed port listen

spice/cfg/tests-variants.cfg, spice/tests/vm_listen.py
=> Initializing subprocess according to ldoktor

spice/cfg/tests-variants.cfg, spice/lib/vm_actions_linux.py
Dependent on https://github.com/avocado-framework/avocado-vt/pull/928
Signed-off-by: Radek Duda rduda@redhat.com
=> Listening address correction

spice/cfg/tests-variants.cfg
=> Rearrange order of TCs by its number in each category (low to high)

requirements.txt
=> Add Pillow version restriction for python 2.6

spice/cfg/spice-base.cfg, spice/cfg/tests-variants.cfg, spice/lib/stest.py, spice/lib/vm_actions_rv.py
Related also to https://github.com/avocado-framework/avocado-vt/pull/967
thanks
=> New testcase: force plaintext channel

spice/cfg/tests-variants.cfg
=> Negative tests for spice server compression value

.travis.yml, requirements-travis.txt, spice/client-tests/rv6.py, spice/client-tests/rv7.py, spice/lib/stest.py, spice/lib/utils.py, spice/lib/vm_actions_rv.py, spice/ovirt/lib4x/driver.py
=> Update yml file to latest inspektor

.travis.yml
testing commit do not merge yet
=> Travis licence

spice/cfg/tests-variants.cfg, spice/cfg/tests.cfg, spice/lib/ios.py, spice/lib/vm_actions_linux.py, spice/tests/rv_gui.py, spice/tests/vm_listen.py
=> rv_gui:Basic corrections, minor version `devel` added

spice/client-tests/rv7.py
Correction of `remote-viewer` GUI test cases.
=> Rv gui review7

spice/cfg/tests-variants.cfg, spice/client-tests/rv7.py, spice/client-tests/simple.py, spice/lib/vm_actions_linux.py, spice/lib/vm_actions_rv.py, spice/tests/rv_gui.py
=> Added minimal version check test cases

spice/client-tests/connect_fail.py
=> New file for version checking

spice/cfg/tests-variants.cfg, spice/client-tests/connect_fail.py, spice/client-tests/help_version.py, spice/lib/vm_actions_linux.py, spice/lib/vm_actions_rv.py
=> Add GUI version test cases.

spice/cfg/tests-variants.cfg, spice/deps/helper_xf.py, spice/lib/vm_actions_linux.py, spice/tests/rv_filexfer.py
=> New testcases: drag and drop file transfer.

spice/cfg/tests-variants.cfg, spice/deps/helper_xf.py, spice/tests/rv_filexfer.py
=> file xfer: progress bar detection

spice/cfg/tests-variants.cfg, spice/tests/rv_filexfer.py
=> filexfer: video files

spice/cfg/tests-variants.cfg, spice/deps/helper_xf.py, spice/tests/rv_filexfer.py
=> filexfer: locked screen negative test

requirements-travis.txt, spice/ovirt/lib4x/user_portal/basictab.py
=> Correction to Travis

spice/cfg/tests-variants.cfg, spice/lib/vm_actions_linux.py, spice/lib/vm_actions_rv.py
=> Some minor chages: ipv6 chk_con, video file for xfer.

spice/cfg/tests.cfg, spice/lib/ios.py, spice/lib/utils.py, spice/lib/vm_actions.py, spice/lib/vm_actions_linux.py, spice/tests/rv_connect.py
=> Introducing rhel8 OS and rhel8 connect test.
